/***
	upperCase / lowerCase string conversion based on Unicode 2.1.8 specification

	## TODO ##
	// ================================================================================
	// Conditional mappings
	// ================================================================================
	// Special case for final form of sigma
	03A3; 03C2; 03A3; 03A3; FINAL; # GREEK CAPITAL LETTER SIGMA
	
	## NODO ##
	// ================================================================================
	// Locale-sensitive mappings
	// ================================================================================
	// Turkish
	0049; 0049; 0131; 0131; tr; # LATIN CAPITAL LETTER I
	0069; 0069; 0130; 0130; tr; # LATIN SMALL LETTER I
***/

(function () {
	var $lowerToUpper = {
			"\xdf": "SS", // LATIN SMALL LETTER SHARP S (SpecialCase)
			"\u0131": "I", // LATIN SMALL LETTER DOTLESS I
			"\u0149": "\u02bcn", // LATIN SMALL LETTER N PRECEDED BY APOSTROPHE (SpecialCase)
			"\u017f": "S", // LATIN SMALL LETTER LONG S
			"\u01c5": "\u01c4", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
			"\u01c8": "\u01c7", // LATIN CAPITAL LETTER L WITH SMALL LETTER J
			"\u01cb": "\u01ca", // LATIN CAPITAL LETTER N WITH SMALL LETTER J
			"\u01f0": "j\u030c", // LATIN SMALL LETTER J WITH CARON (SpecialCase)
			"\u01f2": "\u01f1", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z
			"\u0345": "\u0399", // COMBINING GREEK YPOGEGRAMMENI
			"\u0390": "\u03b9\u0308\u030d", // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS (SpecialCase)
			"\u03b0": "\u03c5\u0308\u030d", // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS (SpecialCase)
			"\u03c2": "\u03a3", // GREEK SMALL LETTER FINAL SIGMA
			"\u03d0": "\u0392", // GREEK BETA SYMBOL
			"\u03d1": "\u0398", // GREEK THETA SYMBOL
			"\u03d5": "\u03a6", // GREEK PHI SYMBOL
			"\u03d6": "\u03a0", // GREEK PI SYMBOL
			"\u03f0": "\u039a", // GREEK KAPPA SYMBOL
			"\u03f1": "\u03a1", // GREEK RHO SYMBOL
			"\u03f2": "\u03a3", // GREEK LUNATE SIGMA SYMBOL
			"\u0587": "\u0535\u0552", // ARMENIAN SMALL LIGATURE ECH YIWN (SpecialCase)
			"\u1e96": "h\u0331", // LATIN SMALL LETTER H WITH LINE BELOW (SpecialCase)
			"\u1e97": "t\u0308", // LATIN SMALL LETTER T WITH DIAERESIS (SpecialCase)
			"\u1e98": "w\u030a", // LATIN SMALL LETTER W WITH RING ABOVE (SpecialCase)
			"\u1e99": "y\u030a", // LATIN SMALL LETTER Y WITH RING ABOVE (SpecialCase)
			"\u1e9a": "a\u02be", // LATIN SMALL LETTER A WITH RIGHT HALF RING (SpecialCase)
			"\u1e9b": "\u1e60", // LATIN SMALL LETTER LONG S WITH DOT ABOVE
			"\u1f50": "\u03c5\u0313", // GREEK SMALL LETTER UPSILON WITH PSILI (SpecialCase)
			"\u1f52": "\u03c5\u0313\u0300", // GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA (SpecialCase)
			"\u1f54": "\u03c5\u0313\u0301", // GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA (SpecialCase)
			"\u1f56": "\u03c5\u0313\u0342", // GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI (SpecialCase)
			"\u1f80": "\u1f08\u03b9", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI (SpecialCase)
			"\u1f81": "\u1f09\u03b9", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f82": "\u1f0a\u03b9", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f83": "\u1f0b\u03b9", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f84": "\u1f0c\u03b9", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f85": "\u1f0d\u03b9", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f86": "\u1f0e\u03b9", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI (SpecialCase)
			"\u1f87": "\u1f0f\u03b9", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI (SpecialCase)
			"\u1f88": "\u1f08\u03b9", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI (SpecialCase)
			"\u1f90": "\u1f28\u03b9", // GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI (SpecialCase)
			"\u1f91": "\u1f29\u03b9", // GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f92": "\u1f2a\u03b9", // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f93": "\u1f2b\u03b9", // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f94": "\u1f2c\u03b9", // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f95": "\u1f2d\u03b9", // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1f96": "\u1f2e\u03b9", // GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI (SpecialCase)
			"\u1f97": "\u1f2f\u03b9", // GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa0": "\u1f68\u03b9", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa1": "\u1f69\u03b9", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa2": "\u1f6a\u03b9", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa3": "\u1f6b\u03b9", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa4": "\u1f6c\u03b9", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa5": "\u1f6d\u03b9", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa6": "\u1f6e\u03b9", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI (SpecialCase)
			"\u1fa7": "\u1f6f\u03b9", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI (SpecialCase)
			"\u1fb2": "\u1f70\u03b9", // GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI (SpecialCase)
			"\u1fb3": "\u0391\u03b9", // GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI (SpecialCase)
			"\u1fb4": "\u1f71\u03b9", // GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI (SpecialCase)
			"\u1fb6": "\u03b1\u0342", // GREEK SMALL LETTER ALPHA WITH PERISPOMENI (SpecialCase)
			"\u1fb7": "\u1fb6\u03b9", // GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI (SpecialCase)
			"\u1fbe": "\u0399", // GREEK PROSGEGRAMMENI
			"\u1fc2": "\u1f74\u03b9", // GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI (SpecialCase)
			"\u1fc3": "\u0397\u03b9", // GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI (SpecialCase)
			"\u1fc4": "\u1f75\u03b9", // GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI (SpecialCase)
			"\u1fc6": "\u03b7\u0342", // GREEK SMALL LETTER ETA WITH PERISPOMENI (SpecialCase)
			"\u1fc7": "\u1fc6\u03b9", // GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI (SpecialCase)
			"\u1fd2": "\u03b9\u0308\u0300", // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA (SpecialCase)
			"\u1fd3": "\u03b9\u0308\u0301", // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA (SpecialCase)
			"\u1fd6": "\u03b9\u0342", // GREEK SMALL LETTER IOTA WITH PERISPOMENI (SpecialCase)
			"\u1fd7": "\u03b9\u0308\u0342", // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI (SpecialCase)
			"\u1fe2": "\u03c5\u0308\u0300", // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA (SpecialCase)
			"\u1fe3": "\u03c5\u0308\u0301", // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA (SpecialCase)
			"\u1fe4": "\u03c1\u0313", // GREEK SMALL LETTER RHO WITH PSILI (SpecialCase)
			"\u1fe6": "\u03c5\u0342", // GREEK SMALL LETTER UPSILON WITH PERISPOMENI (SpecialCase)
			"\u1fe7": "\u03c5\u0308\u0342", // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI (SpecialCase)
			"\u1ff2": "\u1f7c\u03b9", // GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI (SpecialCase)
			"\u1ff3": "\u03a9\u03b9", // GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI (SpecialCase)
			"\u1ff4": "\u1f7d\u03b9", // GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI (SpecialCase)
			"\u1ff6": "\u03c9\u0342", // GREEK SMALL LETTER OMEGA WITH PERISPOMENI (SpecialCase)
			"\u1ff7": "\u1ff6\u03b9", // GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI (SpecialCase)
			"\ufb00": "FF", // LATIN SMALL LIGATURE FF (SpecialCase)
			"\ufb01": "FI", // LATIN SMALL LIGATURE FI (SpecialCase)
			"\ufb02": "FL", // LATIN SMALL LIGATURE FL (SpecialCase)
			"\ufb03": "FFI", // LATIN SMALL LIGATURE FFI (SpecialCase)
			"\ufb04": "FFL", // LATIN SMALL LIGATURE FFL (SpecialCase)
			"\ufb05": "ST", // LATIN SMALL LIGATURE LONG S T (SpecialCase)
			"\ufb06": "ST", // LATIN SMALL LIGATURE ST (SpecialCase)
			"\ufb13": "\u0544\u0546", // ARMENIAN SMALL LIGATURE MEN NOW (SpecialCase)
			"\ufb14": "\u0544\u0535", // ARMENIAN SMALL LIGATURE MEN ECH (SpecialCase)
			"\ufb15": "\u0544\u053b", // ARMENIAN SMALL LIGATURE MEN INI (SpecialCase)
			"\ufb16": "\u054e\u0546", // ARMENIAN SMALL LIGATURE VEW NOW (SpecialCase)
			"\ufb17": "\u0544\u053d", // ARMENIAN SMALL LIGATURE MEN XEH (SpecialCase)
		},
		$upperToLower = {
			"\u0130": "i", // LATIN CAPITAL LETTER I WITH DOT ABOVE
			"\u01c5": "\u01c6", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
			"\u01c8": "\u01c9", // LATIN CAPITAL LETTER L WITH SMALL LETTER J
			"\u01cb": "\u01cc", // LATIN CAPITAL LETTER N WITH SMALL LETTER J
			"\u01f2": "\u01f3", // LATIN CAPITAL LETTER D WITH SMALL LETTER Z
			"\u10a0": "\u10d0", // GEORGIAN CAPITAL LETTER AN
			"\u10a1": "\u10d1", // GEORGIAN CAPITAL LETTER BAN
			"\u10a2": "\u10d2", // GEORGIAN CAPITAL LETTER GAN
			"\u10a3": "\u10d3", // GEORGIAN CAPITAL LETTER DON
			"\u10a4": "\u10d4", // GEORGIAN CAPITAL LETTER EN
			"\u10a5": "\u10d5", // GEORGIAN CAPITAL LETTER VIN
			"\u10a6": "\u10d6", // GEORGIAN CAPITAL LETTER ZEN
			"\u10a7": "\u10d7", // GEORGIAN CAPITAL LETTER TAN
			"\u10a8": "\u10d8", // GEORGIAN CAPITAL LETTER IN
			"\u10a9": "\u10d9", // GEORGIAN CAPITAL LETTER KAN
			"\u10aa": "\u10da", // GEORGIAN CAPITAL LETTER LAS
			"\u10ab": "\u10db", // GEORGIAN CAPITAL LETTER MAN
			"\u10ac": "\u10dc", // GEORGIAN CAPITAL LETTER NAR
			"\u10ad": "\u10dd", // GEORGIAN CAPITAL LETTER ON
			"\u10ae": "\u10de", // GEORGIAN CAPITAL LETTER PAR
			"\u10af": "\u10df", // GEORGIAN CAPITAL LETTER ZHAR
			"\u10b0": "\u10e0", // GEORGIAN CAPITAL LETTER RAE
			"\u10b1": "\u10e1", // GEORGIAN CAPITAL LETTER SAN
			"\u10b2": "\u10e2", // GEORGIAN CAPITAL LETTER TAR
			"\u10b3": "\u10e3", // GEORGIAN CAPITAL LETTER UN
			"\u10b4": "\u10e4", // GEORGIAN CAPITAL LETTER PHAR
			"\u10b5": "\u10e5", // GEORGIAN CAPITAL LETTER KHAR
			"\u10b6": "\u10e6", // GEORGIAN CAPITAL LETTER GHAN
			"\u10b7": "\u10e7", // GEORGIAN CAPITAL LETTER QAR
			"\u10b8": "\u10e8", // GEORGIAN CAPITAL LETTER SHIN
			"\u10b9": "\u10e9", // GEORGIAN CAPITAL LETTER CHIN
			"\u10ba": "\u10ea", // GEORGIAN CAPITAL LETTER CAN
			"\u10bb": "\u10eb", // GEORGIAN CAPITAL LETTER JIL
			"\u10bc": "\u10ec", // GEORGIAN CAPITAL LETTER CIL
			"\u10bd": "\u10ed", // GEORGIAN CAPITAL LETTER CHAR
			"\u10be": "\u10ee", // GEORGIAN CAPITAL LETTER XAN
			"\u10bf": "\u10ef", // GEORGIAN CAPITAL LETTER JHAN
			"\u10c0": "\u10f0", // GEORGIAN CAPITAL LETTER HAE
			"\u10c1": "\u10f1", // GEORGIAN CAPITAL LETTER HE
			"\u10c2": "\u10f2", // GEORGIAN CAPITAL LETTER HIE
			"\u10c3": "\u10f3", // GEORGIAN CAPITAL LETTER WE
			"\u10c4": "\u10f4", // GEORGIAN CAPITAL LETTER HAR
			"\u10c5": "\u10f5", // GEORGIAN CAPITAL LETTER HOE
			"\u1f88": "\u1f80", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI (SpecialCase)
			"\u1f89": "\u1f81", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
			"\u1f8a": "\u1f82", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
			"\u1f8b": "\u1f83", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
			"\u1f8c": "\u1f84", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
			"\u1f8d": "\u1f85", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
			"\u1f8e": "\u1f86", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
			"\u1f8f": "\u1f87", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
			"\u1f98": "\u1f90", // GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
			"\u1f99": "\u1f91", // GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
			"\u1f9a": "\u1f92", // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
			"\u1f9b": "\u1f93", // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
			"\u1f9c": "\u1f94", // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
			"\u1f9d": "\u1f95", // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
			"\u1f9e": "\u1f96", // GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
			"\u1f9f": "\u1f97", // GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
			"\u1fa8": "\u1fa0", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
			"\u1fa9": "\u1fa1", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
			"\u1faa": "\u1fa2", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
			"\u1fab": "\u1fa3", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
			"\u1fac": "\u1fa4", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
			"\u1fad": "\u1fa5", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
			"\u1fae": "\u1fa6", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
			"\u1faf": "\u1fa7", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
			"\u1fbc": "\u1fb3", // GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
			"\u1fcc": "\u1fc3", // GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
			"\u1ffc": "\u1ff3", // GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
		};
	(function () {
		var c,
			bidirectional = {
				A: "a",
				B: "b",
				C: "c",
				D: "d",
				E: "e",
				F: "f",
				G: "g",
				H: "h",
				I: "i",
				J: "j",
				K: "k",
				L: "l",
				M: "m",
				N: "n",
				O: "o",
				P: "p",
				Q: "q",
				R: "r",
				S: "s",
				T: "t",
				U: "u",
				V: "v",
				W: "w",
				X: "x",
				Y: "y",
				Z: "z",
				"\xc0": "\xe0", // LATIN CAPITAL LETTER A WITH GRAVE
				"\xc1": "\xe1", // LATIN CAPITAL LETTER A WITH ACUTE
				"\xc2": "\xe2", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
				"\xc3": "\xe3", // LATIN CAPITAL LETTER A WITH TILDE
				"\xc4": "\xe4", // LATIN CAPITAL LETTER A WITH DIAERESIS
				"\xc5": "\xe5", // LATIN CAPITAL LETTER A WITH RING ABOVE
				"\xc6": "\xe6", // LATIN CAPITAL LETTER AE
				"\xc7": "\xe7", // LATIN CAPITAL LETTER C WITH CEDILLA
				"\xc8": "\xe8", // LATIN CAPITAL LETTER E WITH GRAVE
				"\xc9": "\xe9", // LATIN CAPITAL LETTER E WITH ACUTE
				"\xca": "\xea", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
				"\xcb": "\xeb", // LATIN CAPITAL LETTER E WITH DIAERESIS
				"\xcc": "\xec", // LATIN CAPITAL LETTER I WITH GRAVE
				"\xcd": "\xed", // LATIN CAPITAL LETTER I WITH ACUTE
				"\xce": "\xee", // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
				"\xcf": "\xef", // LATIN CAPITAL LETTER I WITH DIAERESIS
				"\xd0": "\xf0", // LATIN CAPITAL LETTER ETH
				"\xd1": "\xf1", // LATIN CAPITAL LETTER N WITH TILDE
				"\xd2": "\xf2", // LATIN CAPITAL LETTER O WITH GRAVE
				"\xd3": "\xf3", // LATIN CAPITAL LETTER O WITH ACUTE
				"\xd4": "\xf4", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
				"\xd5": "\xf5", // LATIN CAPITAL LETTER O WITH TILDE
				"\xd6": "\xf6", // LATIN CAPITAL LETTER O WITH DIAERESIS
				"\xd8": "\xf8", // LATIN CAPITAL LETTER O WITH STROKE
				"\xd9": "\xf9", // LATIN CAPITAL LETTER U WITH GRAVE
				"\xda": "\xfa", // LATIN CAPITAL LETTER U WITH ACUTE
				"\xdb": "\xfb", // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
				"\xdc": "\xfc", // LATIN CAPITAL LETTER U WITH DIAERESIS
				"\xdd": "\xfd", // LATIN CAPITAL LETTER Y WITH ACUTE
				"\xde": "\xfe", // LATIN CAPITAL LETTER THORN
				"\u0100": "\u0101", // LATIN CAPITAL LETTER A WITH MACRON
				"\u0102": "\u0103", // LATIN CAPITAL LETTER A WITH BREVE
				"\u0104": "\u0105", // LATIN CAPITAL LETTER A WITH OGONEK
				"\u0106": "\u0107", // LATIN CAPITAL LETTER C WITH ACUTE
				"\u0108": "\u0109", // LATIN CAPITAL LETTER C WITH CIRCUMFLEX
				"\u010a": "\u010b", // LATIN CAPITAL LETTER C WITH DOT ABOVE
				"\u010c": "\u010d", // LATIN CAPITAL LETTER C WITH CARON
				"\u010e": "\u010f", // LATIN CAPITAL LETTER D WITH CARON
				"\u0110": "\u0111", // LATIN CAPITAL LETTER D WITH STROKE
				"\u0112": "\u0113", // LATIN CAPITAL LETTER E WITH MACRON
				"\u0114": "\u0115", // LATIN CAPITAL LETTER E WITH BREVE
				"\u0116": "\u0117", // LATIN CAPITAL LETTER E WITH DOT ABOVE
				"\u0118": "\u0119", // LATIN CAPITAL LETTER E WITH OGONEK
				"\u011a": "\u011b", // LATIN CAPITAL LETTER E WITH CARON
				"\u011c": "\u011d", // LATIN CAPITAL LETTER G WITH CIRCUMFLEX
				"\u011e": "\u011f", // LATIN CAPITAL LETTER G WITH BREVE
				"\u0120": "\u0121", // LATIN CAPITAL LETTER G WITH DOT ABOVE
				"\u0122": "\u0123", // LATIN CAPITAL LETTER G WITH CEDILLA
				"\u0124": "\u0125", // LATIN CAPITAL LETTER H WITH CIRCUMFLEX
				"\u0126": "\u0127", // LATIN CAPITAL LETTER H WITH STROKE
				"\u0128": "\u0129", // LATIN CAPITAL LETTER I WITH TILDE
				"\u012a": "\u012b", // LATIN CAPITAL LETTER I WITH MACRON
				"\u012c": "\u012d", // LATIN CAPITAL LETTER I WITH BREVE
				"\u012e": "\u012f", // LATIN CAPITAL LETTER I WITH OGONEK
				"\u0132": "\u0133", // LATIN CAPITAL LIGATURE IJ
				"\u0134": "\u0135", // LATIN CAPITAL LETTER J WITH CIRCUMFLEX
				"\u0136": "\u0137", // LATIN CAPITAL LETTER K WITH CEDILLA
				"\u0139": "\u013a", // LATIN CAPITAL LETTER L WITH ACUTE
				"\u013b": "\u013c", // LATIN CAPITAL LETTER L WITH CEDILLA
				"\u013d": "\u013e", // LATIN CAPITAL LETTER L WITH CARON
				"\u013f": "\u0140", // LATIN CAPITAL LETTER L WITH MIDDLE DOT
				"\u0141": "\u0142", // LATIN CAPITAL LETTER L WITH STROKE
				"\u0143": "\u0144", // LATIN CAPITAL LETTER N WITH ACUTE
				"\u0145": "\u0146", // LATIN CAPITAL LETTER N WITH CEDILLA
				"\u0147": "\u0148", // LATIN CAPITAL LETTER N WITH CARON
				"\u014a": "\u014b", // LATIN CAPITAL LETTER ENG
				"\u014c": "\u014d", // LATIN CAPITAL LETTER O WITH MACRON
				"\u014e": "\u014f", // LATIN CAPITAL LETTER O WITH BREVE
				"\u0150": "\u0151", // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
				"\u0152": "\u0153", // LATIN CAPITAL LIGATURE OE
				"\u0154": "\u0155", // LATIN CAPITAL LETTER R WITH ACUTE
				"\u0156": "\u0157", // LATIN CAPITAL LETTER R WITH CEDILLA
				"\u0158": "\u0159", // LATIN CAPITAL LETTER R WITH CARON
				"\u015a": "\u015b", // LATIN CAPITAL LETTER S WITH ACUTE
				"\u015c": "\u015d", // LATIN CAPITAL LETTER S WITH CIRCUMFLEX
				"\u015e": "\u015f", // LATIN CAPITAL LETTER S WITH CEDILLA
				"\u0160": "\u0161", // LATIN CAPITAL LETTER S WITH CARON
				"\u0162": "\u0163", // LATIN CAPITAL LETTER T WITH CEDILLA
				"\u0164": "\u0165", // LATIN CAPITAL LETTER T WITH CARON
				"\u0166": "\u0167", // LATIN CAPITAL LETTER T WITH STROKE
				"\u0168": "\u0169", // LATIN CAPITAL LETTER U WITH TILDE
				"\u016a": "\u016b", // LATIN CAPITAL LETTER U WITH MACRON
				"\u016c": "\u016d", // LATIN CAPITAL LETTER U WITH BREVE
				"\u016e": "\u016f", // LATIN CAPITAL LETTER U WITH RING ABOVE
				"\u0170": "\u0171", // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
				"\u0172": "\u0173", // LATIN CAPITAL LETTER U WITH OGONEK
				"\u0174": "\u0175", // LATIN CAPITAL LETTER W WITH CIRCUMFLEX
				"\u0176": "\u0177", // LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
				"\u0178": "\xff", // LATIN CAPITAL LETTER Y WITH DIAERESIS
				"\u0179": "\u017a", // LATIN CAPITAL LETTER Z WITH ACUTE
				"\u017b": "\u017c", // LATIN CAPITAL LETTER Z WITH DOT ABOVE
				"\u017d": "\u017e", // LATIN CAPITAL LETTER Z WITH CARON
				"\u0181": "\u0253", // LATIN CAPITAL LETTER B WITH HOOK
				"\u0182": "\u0183", // LATIN CAPITAL LETTER B WITH TOPBAR
				"\u0184": "\u0185", // LATIN CAPITAL LETTER TONE SIX
				"\u0186": "\u0254", // LATIN CAPITAL LETTER OPEN O
				"\u0187": "\u0188", // LATIN CAPITAL LETTER C WITH HOOK
				"\u0189": "\u0256", // LATIN CAPITAL LETTER AFRICAN D
				"\u018a": "\u0257", // LATIN CAPITAL LETTER D WITH HOOK
				"\u018b": "\u018c", // LATIN CAPITAL LETTER D WITH TOPBAR
				"\u018e": "\u01dd", // LATIN CAPITAL LETTER REVERSED E
				"\u018f": "\u0259", // LATIN CAPITAL LETTER SCHWA
				"\u0190": "\u025b", // LATIN CAPITAL LETTER OPEN E
				"\u0191": "\u0192", // LATIN CAPITAL LETTER F WITH HOOK
				"\u0193": "\u0260", // LATIN CAPITAL LETTER G WITH HOOK
				"\u0194": "\u0263", // LATIN CAPITAL LETTER GAMMA
				"\u0196": "\u0269", // LATIN CAPITAL LETTER IOTA
				"\u0197": "\u0268", // LATIN CAPITAL LETTER I WITH STROKE
				"\u0198": "\u0199", // LATIN CAPITAL LETTER K WITH HOOK
				"\u019c": "\u026f", // LATIN CAPITAL LETTER TURNED M
				"\u019d": "\u0272", // LATIN CAPITAL LETTER N WITH LEFT HOOK
				"\u019f": "\u0275", // LATIN CAPITAL LETTER O WITH MIDDLE TILDE
				"\u01a0": "\u01a1", // LATIN CAPITAL LETTER O WITH HORN
				"\u01a2": "\u01a3", // LATIN CAPITAL LETTER OI
				"\u01a4": "\u01a5", // LATIN CAPITAL LETTER P WITH HOOK
				"\u01a6": "\u0280", // LATIN LETTER YR
				"\u01a7": "\u01a8", // LATIN CAPITAL LETTER TONE TWO
				"\u01a9": "\u0283", // LATIN CAPITAL LETTER ESH
				"\u01ac": "\u01ad", // LATIN CAPITAL LETTER T WITH HOOK
				"\u01ae": "\u0288", // LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
				"\u01af": "\u01b0", // LATIN CAPITAL LETTER U WITH HORN
				"\u01b1": "\u028a", // LATIN CAPITAL LETTER UPSILON
				"\u01b2": "\u028b", // LATIN CAPITAL LETTER V WITH HOOK
				"\u01b3": "\u01b4", // LATIN CAPITAL LETTER Y WITH HOOK
				"\u01b5": "\u01b6", // LATIN CAPITAL LETTER Z WITH STROKE
				"\u01b7": "\u0292", // LATIN CAPITAL LETTER EZH
				"\u01b8": "\u01b9", // LATIN CAPITAL LETTER EZH REVERSED
				"\u01bc": "\u01bd", // LATIN CAPITAL LETTER TONE FIVE
				"\u01c4": "\u01c6", // LATIN CAPITAL LETTER DZ WITH CARON
				"\u01c7": "\u01c9", // LATIN CAPITAL LETTER LJ
				"\u01ca": "\u01cc", // LATIN CAPITAL LETTER NJ
				"\u01cd": "\u01ce", // LATIN CAPITAL LETTER A WITH CARON
				"\u01cf": "\u01d0", // LATIN CAPITAL LETTER I WITH CARON
				"\u01d1": "\u01d2", // LATIN CAPITAL LETTER O WITH CARON
				"\u01d3": "\u01d4", // LATIN CAPITAL LETTER U WITH CARON
				"\u01d5": "\u01d6", // LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
				"\u01d7": "\u01d8", // LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
				"\u01d9": "\u01da", // LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
				"\u01db": "\u01dc", // LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
				"\u01de": "\u01df", // LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
				"\u01e0": "\u01e1", // LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
				"\u01e2": "\u01e3", // LATIN CAPITAL LETTER AE WITH MACRON
				"\u01e4": "\u01e5", // LATIN CAPITAL LETTER G WITH STROKE
				"\u01e6": "\u01e7", // LATIN CAPITAL LETTER G WITH CARON
				"\u01e8": "\u01e9", // LATIN CAPITAL LETTER K WITH CARON
				"\u01ea": "\u01eb", // LATIN CAPITAL LETTER O WITH OGONEK
				"\u01ec": "\u01ed", // LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
				"\u01ee": "\u01ef", // LATIN CAPITAL LETTER EZH WITH CARON
				"\u01f1": "\u01f3", // LATIN CAPITAL LETTER DZ
				"\u01f4": "\u01f5", // LATIN CAPITAL LETTER G WITH ACUTE
				"\u01fa": "\u01fb", // LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
				"\u01fc": "\u01fd", // LATIN CAPITAL LETTER AE WITH ACUTE
				"\u01fe": "\u01ff", // LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
				"\u0200": "\u0201", // LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
				"\u0202": "\u0203", // LATIN CAPITAL LETTER A WITH INVERTED BREVE
				"\u0204": "\u0205", // LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
				"\u0206": "\u0207", // LATIN CAPITAL LETTER E WITH INVERTED BREVE
				"\u0208": "\u0209", // LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
				"\u020a": "\u020b", // LATIN CAPITAL LETTER I WITH INVERTED BREVE
				"\u020c": "\u020d", // LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
				"\u020e": "\u020f", // LATIN CAPITAL LETTER O WITH INVERTED BREVE
				"\u0210": "\u0211", // LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
				"\u0212": "\u0213", // LATIN CAPITAL LETTER R WITH INVERTED BREVE
				"\u0214": "\u0215", // LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
				"\u0216": "\u0217", // LATIN CAPITAL LETTER U WITH INVERTED BREVE
				"\u0386": "\u03ac", // GREEK CAPITAL LETTER ALPHA WITH TONOS
				"\u0388": "\u03ad", // GREEK CAPITAL LETTER EPSILON WITH TONOS
				"\u0389": "\u03ae", // GREEK CAPITAL LETTER ETA WITH TONOS
				"\u038a": "\u03af", // GREEK CAPITAL LETTER IOTA WITH TONOS
				"\u038c": "\u03cc", // GREEK CAPITAL LETTER OMICRON WITH TONOS
				"\u038e": "\u03cd", // GREEK CAPITAL LETTER UPSILON WITH TONOS
				"\u038f": "\u03ce", // GREEK CAPITAL LETTER OMEGA WITH TONOS
				"\u0391": "\u03b1", // GREEK CAPITAL LETTER ALPHA
				"\u0392": "\u03b2", // GREEK CAPITAL LETTER BETA
				"\u0393": "\u03b3", // GREEK CAPITAL LETTER GAMMA
				"\u0394": "\u03b4", // GREEK CAPITAL LETTER DELTA
				"\u0395": "\u03b5", // GREEK CAPITAL LETTER EPSILON
				"\u0396": "\u03b6", // GREEK CAPITAL LETTER ZETA
				"\u0397": "\u03b7", // GREEK CAPITAL LETTER ETA
				"\u0398": "\u03b8", // GREEK CAPITAL LETTER THETA
				"\u0399": "\u03b9", // GREEK CAPITAL LETTER IOTA
				"\u039a": "\u03ba", // GREEK CAPITAL LETTER KAPPA
				"\u039b": "\u03bb", // GREEK CAPITAL LETTER LAMDA
				"\u039c": "\u03bc", // GREEK CAPITAL LETTER MU
				"\u039d": "\u03bd", // GREEK CAPITAL LETTER NU
				"\u039e": "\u03be", // GREEK CAPITAL LETTER XI
				"\u039f": "\u03bf", // GREEK CAPITAL LETTER OMICRON
				"\u03a0": "\u03c0", // GREEK CAPITAL LETTER PI
				"\u03a1": "\u03c1", // GREEK CAPITAL LETTER RHO
				"\u03a3": "\u03c3", // GREEK CAPITAL LETTER SIGMA
				"\u03a4": "\u03c4", // GREEK CAPITAL LETTER TAU
				"\u03a5": "\u03c5", // GREEK CAPITAL LETTER UPSILON
				"\u03a6": "\u03c6", // GREEK CAPITAL LETTER PHI
				"\u03a7": "\u03c7", // GREEK CAPITAL LETTER CHI
				"\u03a8": "\u03c8", // GREEK CAPITAL LETTER PSI
				"\u03a9": "\u03c9", // GREEK CAPITAL LETTER OMEGA
				"\u03aa": "\u03ca", // GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
				"\u03ab": "\u03cb", // GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
				"\u03e2": "\u03e3", // COPTIC CAPITAL LETTER SHEI
				"\u03e4": "\u03e5", // COPTIC CAPITAL LETTER FEI
				"\u03e6": "\u03e7", // COPTIC CAPITAL LETTER KHEI
				"\u03e8": "\u03e9", // COPTIC CAPITAL LETTER HORI
				"\u03ea": "\u03eb", // COPTIC CAPITAL LETTER GANGIA
				"\u03ec": "\u03ed", // COPTIC CAPITAL LETTER SHIMA
				"\u03ee": "\u03ef", // COPTIC CAPITAL LETTER DEI
				"\u0401": "\u0451", // CYRILLIC CAPITAL LETTER IO
				"\u0402": "\u0452", // CYRILLIC CAPITAL LETTER DJE
				"\u0403": "\u0453", // CYRILLIC CAPITAL LETTER GJE
				"\u0404": "\u0454", // CYRILLIC CAPITAL LETTER UKRAINIAN IE
				"\u0405": "\u0455", // CYRILLIC CAPITAL LETTER DZE
				"\u0406": "\u0456", // CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
				"\u0407": "\u0457", // CYRILLIC CAPITAL LETTER YI
				"\u0408": "\u0458", // CYRILLIC CAPITAL LETTER JE
				"\u0409": "\u0459", // CYRILLIC CAPITAL LETTER LJE
				"\u040a": "\u045a", // CYRILLIC CAPITAL LETTER NJE
				"\u040b": "\u045b", // CYRILLIC CAPITAL LETTER TSHE
				"\u040c": "\u045c", // CYRILLIC CAPITAL LETTER KJE
				"\u040e": "\u045e", // CYRILLIC CAPITAL LETTER SHORT U
				"\u040f": "\u045f", // CYRILLIC CAPITAL LETTER DZHE
				"\u0410": "\u0430", // CYRILLIC CAPITAL LETTER A
				"\u0411": "\u0431", // CYRILLIC CAPITAL LETTER BE
				"\u0412": "\u0432", // CYRILLIC CAPITAL LETTER VE
				"\u0413": "\u0433", // CYRILLIC CAPITAL LETTER GHE
				"\u0414": "\u0434", // CYRILLIC CAPITAL LETTER DE
				"\u0415": "\u0435", // CYRILLIC CAPITAL LETTER IE
				"\u0416": "\u0436", // CYRILLIC CAPITAL LETTER ZHE
				"\u0417": "\u0437", // CYRILLIC CAPITAL LETTER ZE
				"\u0418": "\u0438", // CYRILLIC CAPITAL LETTER I
				"\u0419": "\u0439", // CYRILLIC CAPITAL LETTER SHORT I
				"\u041a": "\u043a", // CYRILLIC CAPITAL LETTER KA
				"\u041b": "\u043b", // CYRILLIC CAPITAL LETTER EL
				"\u041c": "\u043c", // CYRILLIC CAPITAL LETTER EM
				"\u041d": "\u043d", // CYRILLIC CAPITAL LETTER EN
				"\u041e": "\u043e", // CYRILLIC CAPITAL LETTER O
				"\u041f": "\u043f", // CYRILLIC CAPITAL LETTER PE
				"\u0420": "\u0440", // CYRILLIC CAPITAL LETTER ER
				"\u0421": "\u0441", // CYRILLIC CAPITAL LETTER ES
				"\u0422": "\u0442", // CYRILLIC CAPITAL LETTER TE
				"\u0423": "\u0443", // CYRILLIC CAPITAL LETTER U
				"\u0424": "\u0444", // CYRILLIC CAPITAL LETTER EF
				"\u0425": "\u0445", // CYRILLIC CAPITAL LETTER HA
				"\u0426": "\u0446", // CYRILLIC CAPITAL LETTER TSE
				"\u0427": "\u0447", // CYRILLIC CAPITAL LETTER CHE
				"\u0428": "\u0448", // CYRILLIC CAPITAL LETTER SHA
				"\u0429": "\u0449", // CYRILLIC CAPITAL LETTER SHCHA
				"\u042a": "\u044a", // CYRILLIC CAPITAL LETTER HARD SIGN
				"\u042b": "\u044b", // CYRILLIC CAPITAL LETTER YERU
				"\u042c": "\u044c", // CYRILLIC CAPITAL LETTER SOFT SIGN
				"\u042d": "\u044d", // CYRILLIC CAPITAL LETTER E
				"\u042e": "\u044e", // CYRILLIC CAPITAL LETTER YU
				"\u042f": "\u044f", // CYRILLIC CAPITAL LETTER YA
				"\u0460": "\u0461", // CYRILLIC CAPITAL LETTER OMEGA
				"\u0462": "\u0463", // CYRILLIC CAPITAL LETTER YAT
				"\u0464": "\u0465", // CYRILLIC CAPITAL LETTER IOTIFIED E
				"\u0466": "\u0467", // CYRILLIC CAPITAL LETTER LITTLE YUS
				"\u0468": "\u0469", // CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS
				"\u046a": "\u046b", // CYRILLIC CAPITAL LETTER BIG YUS
				"\u046c": "\u046d", // CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS
				"\u046e": "\u046f", // CYRILLIC CAPITAL LETTER KSI
				"\u0470": "\u0471", // CYRILLIC CAPITAL LETTER PSI
				"\u0472": "\u0473", // CYRILLIC CAPITAL LETTER FITA
				"\u0474": "\u0475", // CYRILLIC CAPITAL LETTER IZHITSA
				"\u0476": "\u0477", // CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
				"\u0478": "\u0479", // CYRILLIC CAPITAL LETTER UK
				"\u047a": "\u047b", // CYRILLIC CAPITAL LETTER ROUND OMEGA
				"\u047c": "\u047d", // CYRILLIC CAPITAL LETTER OMEGA WITH TITLO
				"\u047e": "\u047f", // CYRILLIC CAPITAL LETTER OT
				"\u0480": "\u0481", // CYRILLIC CAPITAL LETTER KOPPA
				"\u0490": "\u0491", // CYRILLIC CAPITAL LETTER GHE WITH UPTURN
				"\u0492": "\u0493", // CYRILLIC CAPITAL LETTER GHE WITH STROKE
				"\u0494": "\u0495", // CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK
				"\u0496": "\u0497", // CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER
				"\u0498": "\u0499", // CYRILLIC CAPITAL LETTER ZE WITH DESCENDER
				"\u049a": "\u049b", // CYRILLIC CAPITAL LETTER KA WITH DESCENDER
				"\u049c": "\u049d", // CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE
				"\u049e": "\u049f", // CYRILLIC CAPITAL LETTER KA WITH STROKE
				"\u04a0": "\u04a1", // CYRILLIC CAPITAL LETTER BASHKIR KA
				"\u04a2": "\u04a3", // CYRILLIC CAPITAL LETTER EN WITH DESCENDER
				"\u04a4": "\u04a5", // CYRILLIC CAPITAL LIGATURE EN GHE
				"\u04a6": "\u04a7", // CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK
				"\u04a8": "\u04a9", // CYRILLIC CAPITAL LETTER ABKHASIAN HA
				"\u04aa": "\u04ab", // CYRILLIC CAPITAL LETTER ES WITH DESCENDER
				"\u04ac": "\u04ad", // CYRILLIC CAPITAL LETTER TE WITH DESCENDER
				"\u04ae": "\u04af", // CYRILLIC CAPITAL LETTER STRAIGHT U
				"\u04b0": "\u04b1", // CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE
				"\u04b2": "\u04b3", // CYRILLIC CAPITAL LETTER HA WITH DESCENDER
				"\u04b4": "\u04b5", // CYRILLIC CAPITAL LIGATURE TE TSE
				"\u04b6": "\u04b7", // CYRILLIC CAPITAL LETTER CHE WITH DESCENDER
				"\u04b8": "\u04b9", // CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE
				"\u04ba": "\u04bb", // CYRILLIC CAPITAL LETTER SHHA
				"\u04bc": "\u04bd", // CYRILLIC CAPITAL LETTER ABKHASIAN CHE
				"\u04be": "\u04bf", // CYRILLIC CAPITAL LETTER ABKHASIAN CHE WITH DESCENDER
				"\u04c1": "\u04c2", // CYRILLIC CAPITAL LETTER ZHE WITH BREVE
				"\u04c3": "\u04c4", // CYRILLIC CAPITAL LETTER KA WITH HOOK
				"\u04c7": "\u04c8", // CYRILLIC CAPITAL LETTER EN WITH HOOK
				"\u04cb": "\u04cc", // CYRILLIC CAPITAL LETTER KHAKASSIAN CHE
				"\u04d0": "\u04d1", // CYRILLIC CAPITAL LETTER A WITH BREVE
				"\u04d2": "\u04d3", // CYRILLIC CAPITAL LETTER A WITH DIAERESIS
				"\u04d4": "\u04d5", // CYRILLIC CAPITAL LIGATURE A IE
				"\u04d6": "\u04d7", // CYRILLIC CAPITAL LETTER IE WITH BREVE
				"\u04d8": "\u04d9", // CYRILLIC CAPITAL LETTER SCHWA
				"\u04da": "\u04db", // CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS
				"\u04dc": "\u04dd", // CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS
				"\u04de": "\u04df", // CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS
				"\u04e0": "\u04e1", // CYRILLIC CAPITAL LETTER ABKHASIAN DZE
				"\u04e2": "\u04e3", // CYRILLIC CAPITAL LETTER I WITH MACRON
				"\u04e4": "\u04e5", // CYRILLIC CAPITAL LETTER I WITH DIAERESIS
				"\u04e6": "\u04e7", // CYRILLIC CAPITAL LETTER O WITH DIAERESIS
				"\u04e8": "\u04e9", // CYRILLIC CAPITAL LETTER BARRED O
				"\u04ea": "\u04eb", // CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS
				"\u04ee": "\u04ef", // CYRILLIC CAPITAL LETTER U WITH MACRON
				"\u04f0": "\u04f1", // CYRILLIC CAPITAL LETTER U WITH DIAERESIS
				"\u04f2": "\u04f3", // CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE
				"\u04f4": "\u04f5", // CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS
				"\u04f8": "\u04f9", // CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS
				"\u0531": "\u0561", // ARMENIAN CAPITAL LETTER AYB
				"\u0532": "\u0562", // ARMENIAN CAPITAL LETTER BEN
				"\u0533": "\u0563", // ARMENIAN CAPITAL LETTER GIM
				"\u0534": "\u0564", // ARMENIAN CAPITAL LETTER DA
				"\u0535": "\u0565", // ARMENIAN CAPITAL LETTER ECH
				"\u0536": "\u0566", // ARMENIAN CAPITAL LETTER ZA
				"\u0537": "\u0567", // ARMENIAN CAPITAL LETTER EH
				"\u0538": "\u0568", // ARMENIAN CAPITAL LETTER ET
				"\u0539": "\u0569", // ARMENIAN CAPITAL LETTER TO
				"\u053a": "\u056a", // ARMENIAN CAPITAL LETTER ZHE
				"\u053b": "\u056b", // ARMENIAN CAPITAL LETTER INI
				"\u053c": "\u056c", // ARMENIAN CAPITAL LETTER LIWN
				"\u053d": "\u056d", // ARMENIAN CAPITAL LETTER XEH
				"\u053e": "\u056e", // ARMENIAN CAPITAL LETTER CA
				"\u053f": "\u056f", // ARMENIAN CAPITAL LETTER KEN
				"\u0540": "\u0570", // ARMENIAN CAPITAL LETTER HO
				"\u0541": "\u0571", // ARMENIAN CAPITAL LETTER JA
				"\u0542": "\u0572", // ARMENIAN CAPITAL LETTER GHAD
				"\u0543": "\u0573", // ARMENIAN CAPITAL LETTER CHEH
				"\u0544": "\u0574", // ARMENIAN CAPITAL LETTER MEN
				"\u0545": "\u0575", // ARMENIAN CAPITAL LETTER YI
				"\u0546": "\u0576", // ARMENIAN CAPITAL LETTER NOW
				"\u0547": "\u0577", // ARMENIAN CAPITAL LETTER SHA
				"\u0548": "\u0578", // ARMENIAN CAPITAL LETTER VO
				"\u0549": "\u0579", // ARMENIAN CAPITAL LETTER CHA
				"\u054a": "\u057a", // ARMENIAN CAPITAL LETTER PEH
				"\u054b": "\u057b", // ARMENIAN CAPITAL LETTER JHEH
				"\u054c": "\u057c", // ARMENIAN CAPITAL LETTER RA
				"\u054d": "\u057d", // ARMENIAN CAPITAL LETTER SEH
				"\u054e": "\u057e", // ARMENIAN CAPITAL LETTER VEW
				"\u054f": "\u057f", // ARMENIAN CAPITAL LETTER TIWN
				"\u0550": "\u0580", // ARMENIAN CAPITAL LETTER REH
				"\u0551": "\u0581", // ARMENIAN CAPITAL LETTER CO
				"\u0552": "\u0582", // ARMENIAN CAPITAL LETTER YIWN
				"\u0553": "\u0583", // ARMENIAN CAPITAL LETTER PIWR
				"\u0554": "\u0584", // ARMENIAN CAPITAL LETTER KEH
				"\u0555": "\u0585", // ARMENIAN CAPITAL LETTER OH
				"\u0556": "\u0586", // ARMENIAN CAPITAL LETTER FEH
				"\u1e00": "\u1e01", // LATIN CAPITAL LETTER A WITH RING BELOW
				"\u1e02": "\u1e03", // LATIN CAPITAL LETTER B WITH DOT ABOVE
				"\u1e04": "\u1e05", // LATIN CAPITAL LETTER B WITH DOT BELOW
				"\u1e06": "\u1e07", // LATIN CAPITAL LETTER B WITH LINE BELOW
				"\u1e08": "\u1e09", // LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
				"\u1e0a": "\u1e0b", // LATIN CAPITAL LETTER D WITH DOT ABOVE
				"\u1e0c": "\u1e0d", // LATIN CAPITAL LETTER D WITH DOT BELOW
				"\u1e0e": "\u1e0f", // LATIN CAPITAL LETTER D WITH LINE BELOW
				"\u1e10": "\u1e11", // LATIN CAPITAL LETTER D WITH CEDILLA
				"\u1e12": "\u1e13", // LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
				"\u1e14": "\u1e15", // LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
				"\u1e16": "\u1e17", // LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
				"\u1e18": "\u1e19", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
				"\u1e1a": "\u1e1b", // LATIN CAPITAL LETTER E WITH TILDE BELOW
				"\u1e1c": "\u1e1d", // LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
				"\u1e1e": "\u1e1f", // LATIN CAPITAL LETTER F WITH DOT ABOVE
				"\u1e20": "\u1e21", // LATIN CAPITAL LETTER G WITH MACRON
				"\u1e22": "\u1e23", // LATIN CAPITAL LETTER H WITH DOT ABOVE
				"\u1e24": "\u1e25", // LATIN CAPITAL LETTER H WITH DOT BELOW
				"\u1e26": "\u1e27", // LATIN CAPITAL LETTER H WITH DIAERESIS
				"\u1e28": "\u1e29", // LATIN CAPITAL LETTER H WITH CEDILLA
				"\u1e2a": "\u1e2b", // LATIN CAPITAL LETTER H WITH BREVE BELOW
				"\u1e2c": "\u1e2d", // LATIN CAPITAL LETTER I WITH TILDE BELOW
				"\u1e2e": "\u1e2f", // LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
				"\u1e30": "\u1e31", // LATIN CAPITAL LETTER K WITH ACUTE
				"\u1e32": "\u1e33", // LATIN CAPITAL LETTER K WITH DOT BELOW
				"\u1e34": "\u1e35", // LATIN CAPITAL LETTER K WITH LINE BELOW
				"\u1e36": "\u1e37", // LATIN CAPITAL LETTER L WITH DOT BELOW
				"\u1e38": "\u1e39", // LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
				"\u1e3a": "\u1e3b", // LATIN CAPITAL LETTER L WITH LINE BELOW
				"\u1e3c": "\u1e3d", // LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
				"\u1e3e": "\u1e3f", // LATIN CAPITAL LETTER M WITH ACUTE
				"\u1e40": "\u1e41", // LATIN CAPITAL LETTER M WITH DOT ABOVE
				"\u1e42": "\u1e43", // LATIN CAPITAL LETTER M WITH DOT BELOW
				"\u1e44": "\u1e45", // LATIN CAPITAL LETTER N WITH DOT ABOVE
				"\u1e46": "\u1e47", // LATIN CAPITAL LETTER N WITH DOT BELOW
				"\u1e48": "\u1e49", // LATIN CAPITAL LETTER N WITH LINE BELOW
				"\u1e4a": "\u1e4b", // LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
				"\u1e4c": "\u1e4d", // LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
				"\u1e4e": "\u1e4f", // LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
				"\u1e50": "\u1e51", // LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
				"\u1e52": "\u1e53", // LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
				"\u1e54": "\u1e55", // LATIN CAPITAL LETTER P WITH ACUTE
				"\u1e56": "\u1e57", // LATIN CAPITAL LETTER P WITH DOT ABOVE
				"\u1e58": "\u1e59", // LATIN CAPITAL LETTER R WITH DOT ABOVE
				"\u1e5a": "\u1e5b", // LATIN CAPITAL LETTER R WITH DOT BELOW
				"\u1e5c": "\u1e5d", // LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
				"\u1e5e": "\u1e5f", // LATIN CAPITAL LETTER R WITH LINE BELOW
				"\u1e60": "\u1e61", // LATIN CAPITAL LETTER S WITH DOT ABOVE
				"\u1e62": "\u1e63", // LATIN CAPITAL LETTER S WITH DOT BELOW
				"\u1e64": "\u1e65", // LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
				"\u1e66": "\u1e67", // LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
				"\u1e68": "\u1e69", // LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
				"\u1e6a": "\u1e6b", // LATIN CAPITAL LETTER T WITH DOT ABOVE
				"\u1e6c": "\u1e6d", // LATIN CAPITAL LETTER T WITH DOT BELOW
				"\u1e6e": "\u1e6f", // LATIN CAPITAL LETTER T WITH LINE BELOW
				"\u1e70": "\u1e71", // LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
				"\u1e72": "\u1e73", // LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
				"\u1e74": "\u1e75", // LATIN CAPITAL LETTER U WITH TILDE BELOW
				"\u1e76": "\u1e77", // LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
				"\u1e78": "\u1e79", // LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
				"\u1e7a": "\u1e7b", // LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
				"\u1e7c": "\u1e7d", // LATIN CAPITAL LETTER V WITH TILDE
				"\u1e7e": "\u1e7f", // LATIN CAPITAL LETTER V WITH DOT BELOW
				"\u1e80": "\u1e81", // LATIN CAPITAL LETTER W WITH GRAVE
				"\u1e82": "\u1e83", // LATIN CAPITAL LETTER W WITH ACUTE
				"\u1e84": "\u1e85", // LATIN CAPITAL LETTER W WITH DIAERESIS
				"\u1e86": "\u1e87", // LATIN CAPITAL LETTER W WITH DOT ABOVE
				"\u1e88": "\u1e89", // LATIN CAPITAL LETTER W WITH DOT BELOW
				"\u1e8a": "\u1e8b", // LATIN CAPITAL LETTER X WITH DOT ABOVE
				"\u1e8c": "\u1e8d", // LATIN CAPITAL LETTER X WITH DIAERESIS
				"\u1e8e": "\u1e8f", // LATIN CAPITAL LETTER Y WITH DOT ABOVE
				"\u1e90": "\u1e91", // LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
				"\u1e92": "\u1e93", // LATIN CAPITAL LETTER Z WITH DOT BELOW
				"\u1e94": "\u1e95", // LATIN CAPITAL LETTER Z WITH LINE BELOW
				"\u1ea0": "\u1ea1", // LATIN CAPITAL LETTER A WITH DOT BELOW
				"\u1ea2": "\u1ea3", // LATIN CAPITAL LETTER A WITH HOOK ABOVE
				"\u1ea4": "\u1ea5", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
				"\u1ea6": "\u1ea7", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
				"\u1ea8": "\u1ea9", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
				"\u1eaa": "\u1eab", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
				"\u1eac": "\u1ead", // LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
				"\u1eae": "\u1eaf", // LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
				"\u1eb0": "\u1eb1", // LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
				"\u1eb2": "\u1eb3", // LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
				"\u1eb4": "\u1eb5", // LATIN CAPITAL LETTER A WITH BREVE AND TILDE
				"\u1eb6": "\u1eb7", // LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
				"\u1eb8": "\u1eb9", // LATIN CAPITAL LETTER E WITH DOT BELOW
				"\u1eba": "\u1ebb", // LATIN CAPITAL LETTER E WITH HOOK ABOVE
				"\u1ebc": "\u1ebd", // LATIN CAPITAL LETTER E WITH TILDE
				"\u1ebe": "\u1ebf", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
				"\u1ec0": "\u1ec1", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
				"\u1ec2": "\u1ec3", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
				"\u1ec4": "\u1ec5", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
				"\u1ec6": "\u1ec7", // LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
				"\u1ec8": "\u1ec9", // LATIN CAPITAL LETTER I WITH HOOK ABOVE
				"\u1eca": "\u1ecb", // LATIN CAPITAL LETTER I WITH DOT BELOW
				"\u1ecc": "\u1ecd", // LATIN CAPITAL LETTER O WITH DOT BELOW
				"\u1ece": "\u1ecf", // LATIN CAPITAL LETTER O WITH HOOK ABOVE
				"\u1ed0": "\u1ed1", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
				"\u1ed2": "\u1ed3", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
				"\u1ed4": "\u1ed5", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
				"\u1ed6": "\u1ed7", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
				"\u1ed8": "\u1ed9", // LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
				"\u1eda": "\u1edb", // LATIN CAPITAL LETTER O WITH HORN AND ACUTE
				"\u1edc": "\u1edd", // LATIN CAPITAL LETTER O WITH HORN AND GRAVE
				"\u1ede": "\u1edf", // LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
				"\u1ee0": "\u1ee1", // LATIN CAPITAL LETTER O WITH HORN AND TILDE
				"\u1ee2": "\u1ee3", // LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
				"\u1ee4": "\u1ee5", // LATIN CAPITAL LETTER U WITH DOT BELOW
				"\u1ee6": "\u1ee7", // LATIN CAPITAL LETTER U WITH HOOK ABOVE
				"\u1ee8": "\u1ee9", // LATIN CAPITAL LETTER U WITH HORN AND ACUTE
				"\u1eea": "\u1eeb", // LATIN CAPITAL LETTER U WITH HORN AND GRAVE
				"\u1eec": "\u1eed", // LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
				"\u1eee": "\u1eef", // LATIN CAPITAL LETTER U WITH HORN AND TILDE
				"\u1ef0": "\u1ef1", // LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
				"\u1ef2": "\u1ef3", // LATIN CAPITAL LETTER Y WITH GRAVE
				"\u1ef4": "\u1ef5", // LATIN CAPITAL LETTER Y WITH DOT BELOW
				"\u1ef6": "\u1ef7", // LATIN CAPITAL LETTER Y WITH HOOK ABOVE
				"\u1ef8": "\u1ef9", // LATIN CAPITAL LETTER Y WITH TILDE
				"\u1f08": "\u1f00", // GREEK CAPITAL LETTER ALPHA WITH PSILI
				"\u1f09": "\u1f01", // GREEK CAPITAL LETTER ALPHA WITH DASIA
				"\u1f0a": "\u1f02", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
				"\u1f0b": "\u1f03", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
				"\u1f0c": "\u1f04", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
				"\u1f0d": "\u1f05", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
				"\u1f0e": "\u1f06", // GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
				"\u1f0f": "\u1f07", // GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
				"\u1f18": "\u1f10", // GREEK CAPITAL LETTER EPSILON WITH PSILI
				"\u1f19": "\u1f11", // GREEK CAPITAL LETTER EPSILON WITH DASIA
				"\u1f1a": "\u1f12", // GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
				"\u1f1b": "\u1f13", // GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
				"\u1f1c": "\u1f14", // GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
				"\u1f1d": "\u1f15", // GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
				"\u1f28": "\u1f20", // GREEK CAPITAL LETTER ETA WITH PSILI
				"\u1f29": "\u1f21", // GREEK CAPITAL LETTER ETA WITH DASIA
				"\u1f2a": "\u1f22", // GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
				"\u1f2b": "\u1f23", // GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
				"\u1f2c": "\u1f24", // GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
				"\u1f2d": "\u1f25", // GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
				"\u1f2e": "\u1f26", // GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
				"\u1f2f": "\u1f27", // GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
				"\u1f38": "\u1f30", // GREEK CAPITAL LETTER IOTA WITH PSILI
				"\u1f39": "\u1f31", // GREEK CAPITAL LETTER IOTA WITH DASIA
				"\u1f3a": "\u1f32", // GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
				"\u1f3b": "\u1f33", // GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
				"\u1f3c": "\u1f34", // GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
				"\u1f3d": "\u1f35", // GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
				"\u1f3e": "\u1f36", // GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
				"\u1f3f": "\u1f37", // GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
				"\u1f48": "\u1f40", // GREEK CAPITAL LETTER OMICRON WITH PSILI
				"\u1f49": "\u1f41", // GREEK CAPITAL LETTER OMICRON WITH DASIA
				"\u1f4a": "\u1f42", // GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
				"\u1f4b": "\u1f43", // GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
				"\u1f4c": "\u1f44", // GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
				"\u1f4d": "\u1f45", // GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
				"\u1f59": "\u1f51", // GREEK CAPITAL LETTER UPSILON WITH DASIA
				"\u1f5b": "\u1f53", // GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
				"\u1f5d": "\u1f55", // GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
				"\u1f5f": "\u1f57", // GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
				"\u1f68": "\u1f60", // GREEK CAPITAL LETTER OMEGA WITH PSILI
				"\u1f69": "\u1f61", // GREEK CAPITAL LETTER OMEGA WITH DASIA
				"\u1f6a": "\u1f62", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
				"\u1f6b": "\u1f63", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
				"\u1f6c": "\u1f64", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
				"\u1f6d": "\u1f65", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
				"\u1f6e": "\u1f66", // GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI
				"\u1f6f": "\u1f67", // GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI
				"\u1fb8": "\u1fb0", // GREEK CAPITAL LETTER ALPHA WITH VRACHY
				"\u1fb9": "\u1fb1", // GREEK CAPITAL LETTER ALPHA WITH MACRON
				"\u1fba": "\u1f70", // GREEK CAPITAL LETTER ALPHA WITH VARIA
				"\u1fbb": "\u1f71", // GREEK CAPITAL LETTER ALPHA WITH OXIA
				"\u1fc8": "\u1f72", // GREEK CAPITAL LETTER EPSILON WITH VARIA
				"\u1fc9": "\u1f73", // GREEK CAPITAL LETTER EPSILON WITH OXIA
				"\u1fca": "\u1f74", // GREEK CAPITAL LETTER ETA WITH VARIA
				"\u1fcb": "\u1f75", // GREEK CAPITAL LETTER ETA WITH OXIA
				"\u1fd8": "\u1fd0", // GREEK CAPITAL LETTER IOTA WITH VRACHY
				"\u1fd9": "\u1fd1", // GREEK CAPITAL LETTER IOTA WITH MACRON
				"\u1fda": "\u1f76", // GREEK CAPITAL LETTER IOTA WITH VARIA
				"\u1fdb": "\u1f77", // GREEK CAPITAL LETTER IOTA WITH OXIA
				"\u1fe8": "\u1fe0", // GREEK CAPITAL LETTER UPSILON WITH VRACHY
				"\u1fe9": "\u1fe1", // GREEK CAPITAL LETTER UPSILON WITH MACRON
				"\u1fea": "\u1f7a", // GREEK CAPITAL LETTER UPSILON WITH VARIA
				"\u1feb": "\u1f7b", // GREEK CAPITAL LETTER UPSILON WITH OXIA
				"\u1fec": "\u1fe5", // GREEK CAPITAL LETTER RHO WITH DASIA
				"\u1ff8": "\u1f78", // GREEK CAPITAL LETTER OMICRON WITH VARIA
				"\u1ff9": "\u1f79", // GREEK CAPITAL LETTER OMICRON WITH OXIA
				"\u1ffa": "\u1f7c", // GREEK CAPITAL LETTER OMEGA WITH VARIA
				"\u1ffb": "\u1f7d", // GREEK CAPITAL LETTER OMEGA WITH OXIA
				"\u2160": "\u2170", // ROMAN NUMERAL ONE
				"\u2161": "\u2171", // ROMAN NUMERAL TWO
				"\u2162": "\u2172", // ROMAN NUMERAL THREE
				"\u2163": "\u2173", // ROMAN NUMERAL FOUR
				"\u2164": "\u2174", // ROMAN NUMERAL FIVE
				"\u2165": "\u2175", // ROMAN NUMERAL SIX
				"\u2166": "\u2176", // ROMAN NUMERAL SEVEN
				"\u2167": "\u2177", // ROMAN NUMERAL EIGHT
				"\u2168": "\u2178", // ROMAN NUMERAL NINE
				"\u2169": "\u2179", // ROMAN NUMERAL TEN
				"\u216a": "\u217a", // ROMAN NUMERAL ELEVEN
				"\u216b": "\u217b", // ROMAN NUMERAL TWELVE
				"\u216c": "\u217c", // ROMAN NUMERAL FIFTY
				"\u216d": "\u217d", // ROMAN NUMERAL ONE HUNDRED
				"\u216e": "\u217e", // ROMAN NUMERAL FIVE HUNDRED
				"\u216f": "\u217f", // ROMAN NUMERAL ONE THOUSAND
				"\u24b6": "\u24d0", // CIRCLED LATIN CAPITAL LETTER A
				"\u24b7": "\u24d1", // CIRCLED LATIN CAPITAL LETTER B
				"\u24b8": "\u24d2", // CIRCLED LATIN CAPITAL LETTER C
				"\u24b9": "\u24d3", // CIRCLED LATIN CAPITAL LETTER D
				"\u24ba": "\u24d4", // CIRCLED LATIN CAPITAL LETTER E
				"\u24bb": "\u24d5", // CIRCLED LATIN CAPITAL LETTER F
				"\u24bc": "\u24d6", // CIRCLED LATIN CAPITAL LETTER G
				"\u24bd": "\u24d7", // CIRCLED LATIN CAPITAL LETTER H
				"\u24be": "\u24d8", // CIRCLED LATIN CAPITAL LETTER I
				"\u24bf": "\u24d9", // CIRCLED LATIN CAPITAL LETTER J
				"\u24c0": "\u24da", // CIRCLED LATIN CAPITAL LETTER K
				"\u24c1": "\u24db", // CIRCLED LATIN CAPITAL LETTER L
				"\u24c2": "\u24dc", // CIRCLED LATIN CAPITAL LETTER M
				"\u24c3": "\u24dd", // CIRCLED LATIN CAPITAL LETTER N
				"\u24c4": "\u24de", // CIRCLED LATIN CAPITAL LETTER O
				"\u24c5": "\u24df", // CIRCLED LATIN CAPITAL LETTER P
				"\u24c6": "\u24e0", // CIRCLED LATIN CAPITAL LETTER Q
				"\u24c7": "\u24e1", // CIRCLED LATIN CAPITAL LETTER R
				"\u24c8": "\u24e2", // CIRCLED LATIN CAPITAL LETTER S
				"\u24c9": "\u24e3", // CIRCLED LATIN CAPITAL LETTER T
				"\u24ca": "\u24e4", // CIRCLED LATIN CAPITAL LETTER U
				"\u24cb": "\u24e5", // CIRCLED LATIN CAPITAL LETTER V
				"\u24cc": "\u24e6", // CIRCLED LATIN CAPITAL LETTER W
				"\u24cd": "\u24e7", // CIRCLED LATIN CAPITAL LETTER X
				"\u24ce": "\u24e8", // CIRCLED LATIN CAPITAL LETTER Y
				"\u24cf": "\u24e9", // CIRCLED LATIN CAPITAL LETTER Z
				"\uff21": "\uff41", // FULLWIDTH LATIN CAPITAL LETTER A
				"\uff22": "\uff42", // FULLWIDTH LATIN CAPITAL LETTER B
				"\uff23": "\uff43", // FULLWIDTH LATIN CAPITAL LETTER C
				"\uff24": "\uff44", // FULLWIDTH LATIN CAPITAL LETTER D
				"\uff25": "\uff45", // FULLWIDTH LATIN CAPITAL LETTER E
				"\uff26": "\uff46", // FULLWIDTH LATIN CAPITAL LETTER F
				"\uff27": "\uff47", // FULLWIDTH LATIN CAPITAL LETTER G
				"\uff28": "\uff48", // FULLWIDTH LATIN CAPITAL LETTER H
				"\uff29": "\uff49", // FULLWIDTH LATIN CAPITAL LETTER I
				"\uff2a": "\uff4a", // FULLWIDTH LATIN CAPITAL LETTER J
				"\uff2b": "\uff4b", // FULLWIDTH LATIN CAPITAL LETTER K
				"\uff2c": "\uff4c", // FULLWIDTH LATIN CAPITAL LETTER L
				"\uff2d": "\uff4d", // FULLWIDTH LATIN CAPITAL LETTER M
				"\uff2e": "\uff4e", // FULLWIDTH LATIN CAPITAL LETTER N
				"\uff2f": "\uff4f", // FULLWIDTH LATIN CAPITAL LETTER O
				"\uff30": "\uff50", // FULLWIDTH LATIN CAPITAL LETTER P
				"\uff31": "\uff51", // FULLWIDTH LATIN CAPITAL LETTER Q
				"\uff32": "\uff52", // FULLWIDTH LATIN CAPITAL LETTER R
				"\uff33": "\uff53", // FULLWIDTH LATIN CAPITAL LETTER S
				"\uff34": "\uff54", // FULLWIDTH LATIN CAPITAL LETTER T
				"\uff35": "\uff55", // FULLWIDTH LATIN CAPITAL LETTER U
				"\uff36": "\uff56", // FULLWIDTH LATIN CAPITAL LETTER V
				"\uff37": "\uff57", // FULLWIDTH LATIN CAPITAL LETTER W
				"\uff38": "\uff58", // FULLWIDTH LATIN CAPITAL LETTER X
				"\uff39": "\uff59", // FULLWIDTH LATIN CAPITAL LETTER Y
				"\uff3a": "\uff5a", // FULLWIDTH LATIN CAPITAL LETTER Z
			};

		// Populate translation tables from bidirectional table
		for (c in bidirectional) $lowerToUpper[($upperToLower[c] = bidirectional[c])] = c;
	})();

	String.prototype["uniUpperCase"] = function () {
		var u,
			i,
			s = "";
		for (i = 0; i < this.length; ++i) (u = $lowerToUpper[this[i]]), (s += u === void 0 ? this[i] : u);
		return s;
	};

	String.prototype["uniLowerCase"] = function () {
		var u,
			i,
			s = "";
		for (i = 0; i < this.length; ++i) (u = $upperToLower[this[i]]), (s += u === void 0 ? this[i] : u);
		return s;
	};
})();

/***
	// TEST conversions towards native toLowerCase and toUpperCase 
	(function() {
		function hexEncode(s) {
		    var r = "";
		    for (var i = 0; i < s.length; i++) {
		        var hex = s.charCodeAt(i).toString(16);
		        r += ("000" + hex).slice(-4);
		    }
		    return "0x"+r
		}

		// Test EVERYTHING
		for (var i = 0; i <= 0xffff; ++i) {
			// Character
			var c = String.fromCharCode(i);
			// To lowercase
			var low = c.toLowerCase();
			var myLow = c.uniLowerCase();
			if (low !== myLow) console.log("toLowerCase compare failed, char " + c + " (" + hexEncode(c) + ") -> " + myLow + " (" + hexEncode(myLow) + ") !== " + low + " (" + hexEncode(low) + ")");
		}

		for (var i = 0; i <= 0xffff; ++i) {
			// Character
			var c = String.fromCharCode(i);
			// To lowercase
			var up = c.toUpperCase();
			var myUp = c.uniUpperCase();
			if (up !== myUp) console.log("toUpperCase compare failed, char " + c + " (" + hexEncode(c) + ") -> " + myUp + " (" + hexEncode(myUp) + ") !== " + up + " (" + hexEncode(up) + ")");
		}
	})();
***/
